apiVersion: v1
kind: Service
metadata:
    name: saanvikitmaypipelinesjavascriptdocker
spec:
    type: LoadBalancer
    ports:
    - port: 80
    selector:
        app: saanvikitmaypipelinesjavascriptdocker
